# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2022-02-04 08:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u0433\u043e\u0440\u043e\u0434')),
            ],
            options={
                'verbose_name': '\u0433\u043e\u0440\u043e\u0434',
                'verbose_name_plural': '\u0433\u043e\u0440\u043e\u0434\u0430',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='\u043d\u043e\u043c\u0435\u0440 \u0441\u0430\u043c\u043e\u043b\u0435\u0442\u0430')),
                ('type_airplane', models.CharField(max_length=30, verbose_name='\u0442\u0438\u043f \u0441\u0430\u043c\u043e\u043b\u0435\u0442\u0430')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0432\u0440\u0435\u043c\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438/\u043f\u0440\u0438\u0431\u044b\u0442\u0438\u044f')),
                ('actual_time', models.DateTimeField(blank=True, null=True, verbose_name='\u0444\u0430\u043a\u0442\u0438\u0447\u0435\u0441\u043a\u043e\u0435 \u0432\u0440\u0435\u043c\u044f')),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_scoreboard.City', verbose_name='\u0433\u043e\u0440\u043e\u0434 \u043f\u0440\u0438\u0431\u044b\u0442\u0438\u044f')),
                ('dispatch_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='flight_scoreboard.City', verbose_name='\u0433\u043e\u0440\u043e\u0434 \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u0440\u0435\u0439\u0441',
                'verbose_name_plural': '\u0440\u0435\u0439\u0441\u044b',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flight_scoreboard.Status'),
        ),
    ]
