# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2022-02-04 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': '\u0441\u0442\u0430\u0442\u0443\u0441', 'verbose_name_plural': '\u0441\u0442\u0430\u0442\u0443\u0441\u044b'},
        ),
    ]
