# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2022-02-04 08:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_scoreboard', '0002_auto_20220204_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAirPlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u0442\u0438\u043f \u0441\u0430\u043c\u043e\u043b\u0435\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u0442\u0438\u043f \u0441\u0430\u043c\u043e\u043b\u0435\u0442\u0430',
                'verbose_name_plural': '\u0442\u0438\u043f\u044b \u0441\u0430\u043c\u043e\u043b\u0435\u0442\u043e\u0432',
            },
        ),
        migrations.RemoveField(
            model_name='flight',
            name='date',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0432\u0440\u0435\u043c\u044f \u043f\u0440\u0438\u0431\u044b\u0442\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0432\u0440\u0435\u043c\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flight_scoreboard.Status', verbose_name='\u0441\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='type_airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_scoreboard.TypeAirPlane'),
        ),
    ]
